
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-ds
spec:
  selector:
    matchLabels:
      app: myapp-ds
  template:
    metadata:
      labels:
        app: myapp-ds
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/hello-app:1.0

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-ds-node
spec:
  selector:
    matchLabels:
      app: myapp-ds1
  template:
    metadata:
      labels:
        app: myapp-ds1
    spec:
      nodeSelector:
        node: hello-world-ns
      containers:
        - name: hello-world
          image: gcr.io/google-samples/hello-app:1.0