apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-secret
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-secret
  template:
    metadata:
      labels:
        app: myapp-secret
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app:1.0
        env:
        - name: app1username
        valueFrom:
          secretKeyRef:
            name: app1
            key: USERNAME
        - name: app1password
        valueFrom:
          secretKeyRef:
            name: app1
            key: PASSWORD
        ports:
        - containerPort: 8080
