apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-image-registry
spec:
  selector:
    matchLabels:
      app: myapp-image
  template:
    metadata:
      labels:
        app: myapp-image
    spec:
      containers:
      - name: myapp
        image: ganeshhp/hello-app:ps
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: private-reg-credy
